### ISSUE TITLE
Crash when running iOS on a Simulator

### ISSUE THREAD

**Issue by gumil** [dniHze/maestro-test-action#50]
The crash happens when running maestro on iOS on a Simulator. WIth the following stacktrace:
```
xcuitest.XCTestDriverClient$XCTestDriverUnreachable: Failed to reach out XCUITest Server
	at xcuitest.XCTestDriverClient$okHttpClient$2.invoke$lambda-2(XCTestDriverClient.kt:75)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at xcuitest.XCTestDriverClient.runningAppId(XCTestDriverClient.kt:137)
	at ios.xctest.XCTestIOSDevice.activeAppId(XCTestIOSDevice.kt:238)
	at ios.xctest.XCTestIOSDevice.contentDescriptor(XCTestIOSDevice.kt:48)
	at ios.LocalIOSDevice.contentDescriptor(LocalIOSDevice.kt:34)
	at maestro.drivers.IOSDriver.contentDescriptor(IOSDriver.kt:181)
	at maestro.ViewHierarchy$Companion.from-c1iYVAs(ViewHierarchy.kt:29)
	at maestro.Maestro.viewHierarchy-prqvCes(Maestro.kt:376)
	at maestro.Maestro$findElementWithTimeout$element$1.invoke(Maestro.kt:401)
	at maestro.Maestro$findElementWithTimeout$element$1.invoke(Maestro.kt:400)
	at maestro.utils.MaestroTimer.withTimeout(MaestroTimer.kt:16)
	at maestro.Maestro.findElementWithTimeout(Maestro.kt:400)
	at maestro.orchestra.Orchestra.findElement(Orchestra.kt:676)
	at maestro.orchestra.Orchestra.findElement$default(Orchestra.kt:658)
	at maestro.orchestra.Orchestra.tapOnElement(Orchestra.kt:587)
	at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:160)
	at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:138)
	at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:92)
	at maestro.orchestra.Orchestra.runFlow$default(Orchestra.kt:73)
	at maestro.cli.runner.TestSuiteInteractor.runFlow(TestSuiteInteractor.kt:141)
	at maestro.cli.runner.TestSuiteInteractor.runTestSuite(TestSuiteInteractor.kt:72)
	at maestro.cli.runner.TestSuiteInteractor.runTestSuite(TestSuiteInteractor.kt:34)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:133)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:115)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:98)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:53)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:115)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:41)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:124)
```

Running it via command line works but running it by specifying the flow file is giving this error.

**Comment by dniHze** [comment]
Hello there. Can you confirm a few details? Is running your tests locally via the command line work fine, or does the execution via actions via `run:` works fine?  Please let me know!

**Comment by gumil** [comment]
> Can you confirm a few details? Is running your tests locally via the command line work fine, or does the execution via actions via `run:` works fine?

Yes both work fine. Only when specifying the flow via the action fails.

**Comment by umesaba** [comment]
Hi , I'm facing the same issue for iOS simulator on maestro 1.24.0 however its working for android. Any updates how to resolve this crash?

**Comment by dniHze** [comment]
Closing as the issue is quite stale. Just leave a comment if you are still affected by the issue.
