### ISSUE TITLE
Maestro iOS driver did not start up in time

### ISSUE THREAD

**Issue by luis-cruzt** [dniHze/maestro-test-action#57]
Hello

I'm having this issue when running the flow on Github Actions, already tried changing to macos-12, macos-12-xl, macos-latest-xlarge, macos-14
```
maestro.MaestroDriverStartupException$IOSDriverTimeoutException: Maestro iOS driver did not start up in time
	at maestro.drivers.IOSDriver.awaitLaunch(IOSDriver.kt:472)
	at maestro.drivers.IOSDriver.open(IOSDriver.kt:53)
	at maestro.Maestro$Companion.ios(Maestro.kt:624)
	at maestro.cli.session.MaestroSessionManager.createIOS(MaestroSessionManager.kt:[31](https://github.com/xxxxx/actions/runs/11716132080/job/32633672377#step:5:34)0)
	at maestro.cli.session.MaestroSessionManager.createMaestro(MaestroSessionManager.kt:159)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:84)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:52)
	at maestro.cli.command.TestCommand.runShardSuite(TestCommand.kt:297)
	at maestro.cli.command.TestCommand.access$runShardSuite(TestCommand.kt:63)
	at maestro.cli.command.TestCommand$handleSessions$1$results$1$1.invokeSuspend(TestCommand.kt:265)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:[33](https://github.com/xxxxx/actions/runs/11716132080/job/32633672377#step:5:36))
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
```

**Comment by luis-cruzt** [comment]
@dniHze Do you know how to fix this?

**Comment by dniHze** [comment]
Any chance you can showcase the repro steps or showcase what your workflow is?

**Comment by pierretoussing** [comment]
Same issue here

**Comment by pierretoussing** [comment]
Action looks like this:

```
ios-e2e-tests:
      needs: ios-build
      runs-on: ['self-hosted', iOS]
      steps:
        - uses: actions/checkout@v4
        - name: Download Build
          id: download_build
          uses: actions/download-artifact@v4
          with:
            name: ios-build
            path: ${{ runner.workspace }}/ios-build
        - name: Rename Build
          run: mv ${{ runner.workspace }}/ios-build ${{ runner.workspace }}/ios-build.app
        - uses: actions/setup-java@v3
          with:
            distribution: 'adopt'
            java-version: '11'
        - uses: futureware-tech/simulator-action@v2
          with:
            model: 'iPhone 15 Pro'
        - uses: dniHze/maestro-test-action@v1
          with:
            flow: ${{ runner.workspace }}/app/.maestro/tests/tasks/CreateTask.yaml
            report: ./ios-maestro-report.xml
            env: |
              APP_ID=${{ needs.setup-env.outputs.ios_app_id }}
              PHONE_NUMBER=${{ secrets.MAESTRO_USER_1_PHONE_NUMBER }}
              LOGIN_CODE=${{ secrets.MAESTRO_USER_1_LOGIN_CODE }}
```

**Comment by dniHze** [comment]
Thanks for getting back to me with a log. I plan to upgrade the runner soon, so I will try to check if the newer version broke something since the last time I checked.

**Comment by pierretoussing** [comment]
If you need any more logs, please let me know!

**Comment by pierretoussing** [comment]
I see the same behaviour for Android:

```
/usr/local/lib/android/sdk/platform-tools/adb -s emulator-5554 shell getprop sys.boot_completed
  1
  Emulator booted.
  /usr/local/lib/android/sdk/platform-tools/adb -s emulator-5554 shell input keyevent 82
  INFO    | Boot completed in 530171 ms
  INFO    | Increasing screen off timeout, logcat buffer size to 2M.
  Disabling animations.
  /usr/local/lib/android/sdk/platform-tools/adb -s emulator-5554 shell settings put global window_animation_scale 0.0
  /usr/local/lib/android/sdk/platform-tools/adb -s emulator-5554 shell settings put global transition_animation_scale 0.0
  /usr/local/lib/android/sdk/platform-tools/adb -s emulator-5554 shell settings put global animator_duration_scale 0.0
/usr/bin/sh -c maestro test --format=junit --output=report.xml --no-ansi /home/runner/work/benetics/benetics/app/.maestro -e APP_ID=com.benetics.dev -e PHONE_NUMBER=*** -e LOGIN_CODE=*** -e SIGN_UP_PHONE_NUMBER=*** -e SIGN_UP_LOGIN_CODE=***
CI detected, analytics was automatically enabled.
To opt out, set MAESTRO_CLI_NO_ANALYTICS environment variable to any value before running Maestro.
Maestro Android driver did not start up in time  ---  emulator [ emulator-5554 ] & port  [ dadb.open( tcp:7001 ) ]
The stack trace was:
maestro.MaestroDriverStartupException$AndroidDriverTimeoutException: Maestro Android driver did not start up in time  ---  emulator [ emulator-5554 ] & port  [ dadb.open( tcp:7001 ) ]
	at maestro.drivers.AndroidDriver.awaitLaunch(AndroidDriver.kt:156)
	at maestro.drivers.AndroidDriver.open(AndroidDriver.kt:89)
	at maestro.Maestro$Companion.android(Maestro.kt:631)
	at maestro.cli.session.MaestroSessionManager.createAndroid(MaestroSessionManager.kt:269)
	at maestro.cli.session.MaestroSessionManager.createMaestro(MaestroSessionManager.kt:154)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:85)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:53)
	at maestro.cli.command.TestCommand.runShardSuite(TestCommand.kt:297)
	at maestro.cli.command.TestCommand.access$runShardSuite(TestCommand.kt:63)
	at maestro.cli.command.TestCommand$handleSessions$1$results$1$1.invokeSuspend(TestCommand.kt:265)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:[693]
```

With this action:

```
android-e2e-tests:	
      needs: 	
        - setup-env	
        - android-build	
      runs-on: 'ubuntu-latest'	
      steps:	
        - uses: actions/checkout@v4	
        - name: Download Build	
          id: download_build	
          uses: actions/download-artifact@v4	
          with:	
            name: android-build	
            path: ${{ runner.workspace }}/android-build	
        - name: Rename Build	
          run: mv ${{ runner.workspace }}/android-build/*.apk ${{ runner.workspace }}/android-build/benetics.apk	
        - uses: actions/setup-java@v3
          with:
            distribution: 'adopt'
            java-version: '11'
        - uses: dniHze/maestro-test-action@v1
        - uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 33
            arch: x86_64
            ram-size: 2048M
            target: default
            script: maestro test --format=junit --output=report.xml --no-ansi ${{ runner.workspace }}/app/.maestro
```

**Comment by tomruijgrok** [comment]
Any updates on this?

**Comment by luis-cruzt** [comment]
I’ve managed to fix it. I’m using this action on a private repository, so I had to tweak my workflow. I used another GitHub Action to run the emulator. The only issue is that KVM is only available for public repositories for free (See [this comment](https://github.com/ReactiveCircus/android-emulator-runner/issues/367#issuecomment-1907162844)), so I had to change the runner to ubuntu-latest, and it worked.

I hope this helps someone else too.
```
name: Run Integration Tests

# Trigger the workflow when a pull request is opened or updated
# for any branch that contains uat
on:
  pull_request:
    branches:
      - 'uat'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MAESTRO_DRIVER_STARTUP_TIMEOUT: 60000
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 🏗 Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: 🏗 Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

       # Other actions
      
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
    
      - uses: dniHze/maestro-test-action@v1
      - name: Android Emulator Runner
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33          
          arch: x86_64
          profile: Nexus 6
          script: |          
            flutter pub get
            flutter build apk
            flutter install
            maestro test integration_tests
```

**Comment by srenghongpor** [comment]
any update on IOS ?
